# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ffa3df71ab9c0aa38a621f5981ede9cb"
name = "bundle-cart-tranform-demo"
handle = "bundle-cart-tranform-demo"
application_url = "https://repair-remix-court-heart.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "extensiontestingstore.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,write_cart_transforms,write_products,read_products,read_product_listings"

[auth]
redirect_urls = [
  "https://repair-remix-court-heart.trycloudflare.com/auth/callback",
  "https://repair-remix-court-heart.trycloudflare.com/auth/shopify/callback",
  "https://repair-remix-court-heart.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
